# Generated by Django 3.2.6 on 2023-10-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_auto_20231026_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmain',
            name='image',
            field=models.ImageField(max_length=350, null=True, upload_to='product', verbose_name='Ürün Kart Resmi'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='appMy.productmain', verbose_name='Ürün'),
        ),
    ]
