# Generated by Django 4.2 on 2023-11-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_productmain_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_cod',
            field=models.CharField(max_length=50, null=True, verbose_name='Renk Kodu'),
        ),
    ]
