# Generated by Django 4.2 on 2023-11-07 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appMy', '0006_color_color_cod'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanity', models.IntegerField(default=0, verbose_name='Adet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMy.productinfo', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
