# Generated by Django 4.2 on 2023-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_basketshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketshop',
            name='total_price',
            field=models.FloatField(default=0, verbose_name='Toplam Fiyat'),
        ),
    ]
