# Generated by Django 4.2.6 on 2023-10-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='emailactive',
            field=models.CharField(max_length=50, null=True, verbose_name='Email Active'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Kullanıcı Adresi'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='default/user.png', max_length=300, upload_to='user', verbose_name='Profile'),
        ),
    ]
