# Generated by Django 4.2.6 on 2023-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0002_userinfo_emailactive_alter_userinfo_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='emailactive',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email Active'),
        ),
    ]
